Repository silverstripe/silverstripe-login-forms, pull requests merged in 2019-08, with the labels that each got.

#36 FIX Introduce more css vars for more specific styling
  client/dist/styles/bundle.css
  client/src/styles/login-form.scss
  client/src/styles/login-forms-variables.scss
Labels: affects/v4, change/patch

#35 NEW Convert login-forms to base off of bootstrap instead of framework/admin styles
  client/dist/styles/bundle.css
  client/src/styles/admin-overrides.scss
  client/src/styles/bundle.scss
  client/src/styles/typography.scss
  package.json
  src/EnablerExtension.php
  yarn.lock
Labels: affects/v3, change/minor

#37 FIX Login Forms UI now scales in width correctly in all browsers
  client/dist/styles/bundle.css
  client/src/styles/layout.scss
Labels: affects/v4, change/patch

#39 Improve link styling in dark mode
  client/dist/styles/bundle.css
  client/src/styles/login-forms-variables.scss
  client/src/styles/typography.scss
Labels: affects/v4, change/minor

#40 FIX Text input elements should stay the same colour when focussed
  client/dist/styles/bundle.css
  client/src/styles/login-form.scss
Labels: affects/v4, change/patch

#43 FIX Separate header into its own include template
  themes/login-forms/templates/AppHeader.ss
  themes/login-forms/templates/Security.ss
Labels: affects/v3, change/patch

#42 FIX Separate header into its own include template
  themes/login-forms/templates/AppHeader.ss
  themes/login-forms/templates/Security.ss
Labels: affects/v4, change/patch
